name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiad image
      run: docker build . --file Dockerfile --tag unitia:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen Image Tag 
      run: docker tag unitia:lion registry-1.docker.io/winnovature/unitia:lion
    - uses: docker/build-push-action@v1
    - name: Docker Login 
      run: docker login registry-1.docker.io -u winnovature -p R3qErf%a1
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen PushTag 
      run: docker push registry-1.docker.io/winnovature/unitia:lion