name: Unitia Docker Image CI

### Variable {{tagname $(date +%s)}}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unitia:{{tagname}}
    - uses: docker/build-push-action@v1
    - name: Docker Image Tag 
      run: docker tag unitia:{{tagname}} winnovature/unitia:{{tagname}}
    - uses: docker/build-push-action@v1
    - name: Docker PushTag 
      run: docker push winnovature/unitia:{{tagname}}