name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unitia:tiger
    - uses: docker/build-push-action@v1
    - name: Docker Image Tag 
      run: docker tag unitia:tiger winnovature/unitia:tiger
    - uses: docker/build-push-action@v1
    - name: Docker Login 
      run: docker login https://hub.docker.com/ -u winnovature -p R3qErf%a1
    - uses: docker/build-push-action@v1
    - name: Docker PushTag 
      run: docker push winnovature/unitia:tiger


