name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiaweb image
      run: docker build . --file Dockerfileunitiaweb --tag unitiaweb:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiaweb Image Tag 
      run: docker tag unitiaweb:lion registry-1.docker.io/winnovature/unitiaweb:lion
    - uses: docker/build-push-action@v1
    - name: Docker Login 
      run: docker login registry-1.docker.io -u winnovature -p R3qErf%a1
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiaweb PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiaweb:lion


