name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
    - name: Docker Login 
      run: docker login registry-1.docker.io -u winnovature -p R3qErf%a1
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiadngen image
      run: docker build . --file Dockerfileunitiadngen --tag unitiadngen:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen Image Tag 
      run: docker tag unitiadngen:lion registry-1.docker.io/winnovature/unitiadngen:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiadngen:lion
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiadnreceiver image
      run: docker build . --file Dockerfileunitiadnreceiver --tag unitiadnreceiver:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadnreceiver Image Tag 
      run: docker tag unitiadnreceiver:lion registry-1.docker.io/winnovature/unitiadnreceiver:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadnreceiver PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiadnreceiver:lion
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiacore image
      run: docker build . --file Dockerfileunitiacore --tag unitiacore:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiacore Image Tag 
      run: docker tag unitiacore:lion registry-1.docker.io/winnovature/unitiacore:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiacore PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiacore:lion
    - name: Build the Dockerfileunitiahttpd image
      run: docker build . --file Dockerfileunitiahttpd --tag unitiahttpd:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiahttpd Image Tag 
      run: docker tag unitiahttpd:lion registry-1.docker.io/winnovature/unitiahttpd:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiahttpd PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiahttpd:lion
