name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build the source code by maven
      run : mvn install
    - uses: actions/checkout@v2
    - name: list out the directories
      run : ls -lrt
    - uses: actions/checkout@v2
    - name: list out the directories api
      run : ls -lrt api
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unitia:$(date +%s)
