name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiaweb image
      run: docker build . --file Dockerfileunitiaweb --tag unitiaweb:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiaweb Image Tag 
      run: docker tag unitiaweb:lion registry-1.docker.io/winnovature/unitiaweb:lion
    - uses: docker/build-push-action@v1
    - name: Docker Login 
      run: docker login registry-1.docker.io -u winnovature -p R3qErf%a1
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiaweb PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiaweb:lion
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiadngen image
      run: docker build . --file Dockerfileunitiadngen --tag unitiadngen:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen Image Tag 
      run: docker tag unitiadngen:lion registry-1.docker.io/winnovature/unitiadngen:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadngen PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiadngen:lion
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiadnreceiver image
      run: docker build . --file Dockerfileunitiadnreceiver --tag unitiadnreceiver:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadnreceiver Image Tag 
      run: docker tag unitiadnreceiver:lion registry-1.docker.io/winnovature/unitiadnreceiver:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadnreceiver PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiadnreceiver:lion
    - uses: actions/checkout@v2
    - name: Build the Dockerfileunitiadncore image
      run: docker build . --file Dockerfileunitiadncore --tag unitiadncore:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadncore Image Tag 
      run: docker tag unitiadncore:lion registry-1.docker.io/winnovature/unitiadncore:lion
    - uses: docker/build-push-action@v1
    - name: Dockerfileunitiadncore PushTag 
      run: docker push registry-1.docker.io/winnovature/unitiadncore:lion
