name: Unitia Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unitia:$(date +%s)
    - uses: docker/build-push-action@v1
    - name: Push Docker Image to Repository  
	with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: myorg/myrepository
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}